[package]
name = "esp32"
version = "0.1.0"
authors = ["Pironium <94836916+Pironium-dev@users.noreply.github.com>"]
edition = "2024"

[[bin]]
name = "esp32"
harness = false # do not use the built-in cargo test harness -> resolve rust-analyzer errors

[dependencies]
log = "0.4"
esp-idf-svc = { version = "0.52.1", features = ["critical-section", "embassy-time-driver", "embassy-sync"] }
# Remove `generic-queue-8` if you plan to use `embassy-time` WITH `embassy-executor`
embassy-time = { version = "0.5", features = ["generic-queue-8"] }
embassy-futures = "0.1.2"
embassy-executor = { version = "0.9.1", features = ["arch-std"] }

[build-dependencies]
embuild = "0.33"
dotenvy = "0.15.7"
